-- Agent Reports Table
-- Created: 2026-01-29
-- Purpose: Store GTM reports generated by the single-agent system with tool use
--
-- Features:
-- - Web search and RapidAPI tool usage tracking
-- - Cost and token metrics
-- - Full report JSON and rendered HTML storage

-- ============================================
-- Agent Reports
-- ============================================

CREATE TABLE agent_reports (
  id TEXT PRIMARY KEY,                    -- 'agrep_' prefix
  interview_id TEXT NOT NULL,
  user_id TEXT NOT NULL,

  -- Status tracking
  -- Values: PENDING | GENERATING | READY | FAILED
  status TEXT NOT NULL DEFAULT 'PENDING',
  progress INTEGER DEFAULT 0,             -- 0-100
  error TEXT,

  -- Generated Data
  gtm_report TEXT,                        -- Full report JSON
  html_report TEXT,                       -- Rendered HTML
  brand_name TEXT,

  -- Tool Usage Tracking
  web_searches_count INTEGER DEFAULT 0,
  rapidapi_calls_count INTEGER DEFAULT 0,
  tool_results TEXT,                      -- Store tool outputs for reference (JSON)

  -- Metrics
  total_input_tokens INTEGER DEFAULT 0,
  total_output_tokens INTEGER DEFAULT 0,
  total_cost_cents INTEGER DEFAULT 0,
  model_id TEXT,
  generation_time_seconds INTEGER,

  -- Timestamps
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  generation_started_at DATETIME,
  generation_completed_at DATETIME,

  FOREIGN KEY (interview_id) REFERENCES interviews(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Indexes for common queries
CREATE INDEX idx_agent_reports_interview ON agent_reports(interview_id);
CREATE INDEX idx_agent_reports_user ON agent_reports(user_id, created_at DESC);
CREATE INDEX idx_agent_reports_status ON agent_reports(status);
