-- OpenClaw Nervous System Tables
-- Phase A: Action cards + Heartbeat tracking
-- Phase B.2: Notification preferences + logs

-- Heartbeat run history
CREATE TABLE IF NOT EXISTS openclaw_heartbeats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id VARCHAR(64) NOT NULL,
  started_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP,
  metrics_snapshot JSONB,
  rules_triggered JSONB,
  actions_generated INTEGER DEFAULT 0,
  actions_auto_executed INTEGER DEFAULT 0,
  status VARCHAR(20) DEFAULT 'running',
  error_message TEXT
);

CREATE INDEX idx_heartbeats_client ON openclaw_heartbeats(client_id);
CREATE INDEX idx_heartbeats_started ON openclaw_heartbeats(started_at DESC);

-- Action cards (generated by heartbeat, acted on by user or auto)
CREATE TABLE IF NOT EXISTS openclaw_actions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id VARCHAR(64) NOT NULL,
  card_type VARCHAR(64) NOT NULL,
  trust_level VARCHAR(4) NOT NULL,
  severity VARCHAR(16) NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  impact TEXT,
  action_type VARCHAR(64),
  action_target_id VARCHAR(128),
  action_params JSONB,
  status VARCHAR(20) DEFAULT 'pending',
  rejected_reason TEXT,
  before_state JSONB,
  created_at TIMESTAMP DEFAULT NOW(),
  executed_at TIMESTAMP,
  responded_at TIMESTAMP,
  heartbeat_id UUID REFERENCES openclaw_heartbeats(id)
);

CREATE INDEX idx_actions_client ON openclaw_actions(client_id);
CREATE INDEX idx_actions_status ON openclaw_actions(status);
CREATE INDEX idx_actions_created ON openclaw_actions(created_at DESC);
CREATE INDEX idx_actions_trust ON openclaw_actions(trust_level);

-- Notification preferences (per client)
CREATE TABLE IF NOT EXISTS openclaw_notification_prefs (
  client_id VARCHAR(64) PRIMARY KEY,
  frequency VARCHAR(20) DEFAULT 'weekly',
  email VARCHAR(255),
  whatsapp VARCHAR(20),
  quiet_start SMALLINT DEFAULT 23,
  quiet_end SMALLINT DEFAULT 8,
  emergency_override BOOLEAN DEFAULT true,
  daily_digest BOOLEAN DEFAULT false,
  milestone_celebrations BOOLEAN DEFAULT true,
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Notification send log
CREATE TABLE IF NOT EXISTS openclaw_notification_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id VARCHAR(64) NOT NULL,
  channel VARCHAR(16) NOT NULL,
  template VARCHAR(64) NOT NULL,
  action_id UUID REFERENCES openclaw_actions(id),
  sent_at TIMESTAMP DEFAULT NOW(),
  delivered BOOLEAN,
  opened BOOLEAN,
  clicked BOOLEAN
);

CREATE INDEX idx_notif_log_client ON openclaw_notification_log(client_id);
CREATE INDEX idx_notif_log_sent ON openclaw_notification_log(sent_at DESC);
